### ISSUE TITLE
[Bug]: Breaking water trough crashed game

### ISSUE THREAD

**Issue by Joequidae** [cavecomputing/SWEM-Beta#100]
### What happened?

i placed three troughs in a row, none of them connected, and then broke the center one and it crashed the game.

### What should happen?

water trough should connect initially and not crash when breaking them

### Mods

just swem and geckolib

### SWEM Version

0.1.2.1

### Singleplayer or Multiplayer

- [X] Singleplayer
- [ ] Multiplayer
- [ ] Other (Please add a comment to the issue where this is happening)

### OS

Windows

### Relevant log output

```shell
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 11/5/21 7:20 PM
Description: Unexpected error

java.lang.IllegalArgumentException: Cannot get property DirectionProperty{name=facing, clazz=class net.minecraft.util.Direction, values=[north, south, west, east]} as it does not exist in Block{minecraft:air}
	at net.minecraft.state.StateHolder.func_177229_b(SourceFile:95) ~[?:?] {re:mixin,re:classloading}
	at com.alaharranhonor.swem.blocks.NonParallelBlock.func_196271_a(NonParallelBlock.java:123) ~[?:1.16.5-0.1.2.1-b] {re:classloading}
	at com.alaharranhonor.swem.blocks.WaterTroughBlock.func_196271_a(WaterTroughBlock.java:48) ~[?:1.16.5-0.1.2.1-b] {re:classloading}
	at net.minecraft.block.AbstractBlock$AbstractBlockState.func_196956_a(AbstractBlock.java:657) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.block.AbstractBlock$AbstractBlockState.func_241482_a_(AbstractBlock.java:597) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.world.World.markAndNotifyBlock(World.java:245) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.World.func_241211_a_(World.java:212) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.World.func_180501_a(World.java:176) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraftforge.common.extensions.IForgeBlock.removedByPlayer(IForgeBlock.java:200) ~[?:?] {re:classloading,re:mixin}
	at net.minecraftforge.common.extensions.IForgeBlockState.removedByPlayer(IForgeBlockState.java:157) ~[?:?] {re:classloading}
	at net.minecraft.client.multiplayer.PlayerController.func_187103_a(PlayerController.java:112) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.multiplayer.PlayerController.func_180511_b(PlayerController.java:134) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_147116_af(Minecraft.java:1311) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:1641) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1460) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:953) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.1.0.jar:36.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$444/570422884.call(Unknown Source) [forge-1.16.5-36.1.0.jar:36.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.state.StateHolder.func_177229_b(SourceFile:95) ~[?:?] {re:mixin,re:classloading}
	at com.alaharranhonor.swem.blocks.NonParallelBlock.func_196271_a(NonParallelBlock.java:123) ~[?:1.16.5-0.1.2.1-b] {re:classloading}
	at com.alaharranhonor.swem.blocks.WaterTroughBlock.func_196271_a(WaterTroughBlock.java:48) ~[?:1.16.5-0.1.2.1-b] {re:classloading}
	at net.minecraft.block.AbstractBlock$AbstractBlockState.func_196956_a(AbstractBlock.java:657) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.block.AbstractBlock$AbstractBlockState.func_241482_a_(AbstractBlock.java:597) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.world.World.markAndNotifyBlock(World.java:245) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.World.func_241211_a_(World.java:212) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.World.func_180501_a(World.java:176) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraftforge.common.extensions.IForgeBlock.removedByPlayer(IForgeBlock.java:200) ~[?:?] {re:classloading,re:mixin}
	at net.minecraftforge.common.extensions.IForgeBlockState.removedByPlayer(IForgeBlockState.java:157) ~[?:?] {re:classloading}
	at net.minecraft.client.multiplayer.PlayerController.func_187103_a(PlayerController.java:112) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.multiplayer.PlayerController.func_180511_b(PlayerController.java:134) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_147116_af(Minecraft.java:1311) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:1641) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['jo_wulf'/570, l='ClientLevel', x=-252.65, y=4.00, z=-171.86]]
	Chunk stats: Client Chunk Cache: 1225, 899
	Level dimension: minecraft:overworld
	Level spawn location: World: (-240,4,-192), Chunk: (at 0,0,0 in -15,-12; contains blocks -240,0,-192 to -225,255,-177), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 22428 game time, 22428 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:447) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2029) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:628) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.1.0.jar:36.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$444/570422884.call(Unknown Source) [forge-1.16.5-36.1.0.jar:36.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}


-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1104034368 bytes (1052 MB) / 2046820352 bytes (1952 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 12
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.1.0.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.0.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.1.0.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.0.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.1.0.jar fml TRANSFORMATIONSERVICE 
	FML: 36.1
	Forge: net.minecraftforge:36.1.0
	FML Language Providers: 
		javafml@36.1
		minecraft@1
	Mod List: 
		forge-1.16.5-36.1.0-client.jar                    |Minecraft                     |minecraft                     |1.16.5              |DONE      |NOSIGNATURE
		forge-1.16.5-36.1.0-universal.jar                 |Forge                         |forge                         |36.1.0              |DONE      |22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		geckolib-forge-1.16.5-3.0.35.jar                  |GeckoLib                      |geckolib3                     |3.0.35              |DONE      |NOSIGNATURE
		swem-1.16.5-0.1.2.1-b.jar                         |Star Worm Equestrian Mod      |swem                          |1.16.5-0.1.2.1-b    |DONE      |NOSIGNATURE
	Crash Report UUID: e45c501e-07b0-4d2b-85bc-140772e8b613
	Launched Version: 1.16.5-forge-36.1.0
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 970/PCIe/SSE2 GL version 4.6.0 NVIDIA 456.71, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: 
	Current Language: English (US)
	CPU: 12x Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz
```

**Comment by Shrimpez** [comment]
Also happening to me!

**Comment by MagnusHJensen** [comment]
This should be fixed with the newer release.

Please reopen, if the crash occurs with the newer version.
