### ISSUE TITLE
[Bug]: Game crashes when opening stats

### ISSUE THREAD

**Issue by Psychicwolf** [cavecomputing/SWEM-Beta#149]
### What happened?

Using the Callable Horses mod, attempting to look at the horse's stats with the hotkey freezes and then crashes the game.

### What should happen?

The game shouldn't crash and perhaps instead open up the regular SWEM horse stat hud.

### Mods

The most recent modpack as of 12/19/21 for the server without Xaeros minimap and Xaeros world map

### SWEM Version

1.16.5-0.2.3.9-b

### Singleplayer or Multiplayer

- [X] Singleplayer
- [ ] Multiplayer
- [ ] Other (Please add a comment to the issue where this is happening)

### OS

Windows

### Relevant log output

```shell
Time: 12/19/21 9:33 PM
Description: Rendering entity in world

java.lang.ClassCastException: net.minecraft.item.SaddleItem cannot be cast to com.alaharranhonor.swem.items.tack.HalterItem
	at com.alaharranhonor.swem.entity.layers.HalterLayer.render(HalterLayer.java:45) ~[?:1.16.5-0.2.3.9-b] {re:classloading}
	at com.alaharranhonor.swem.entity.layers.HalterLayer.render(HalterLayer.java:32) ~[?:1.16.5-0.2.3.9-b] {re:classloading}
	at software.bernie.geckolib3.renderers.geo.GeoEntityRenderer.render(GeoEntityRenderer.java:151) ~[?:3.0.35] {re:classloading}
	at com.alaharranhonor.swem.entity.render.SWEMHorseRender.render(SWEMHorseRender.java:82) ~[?:1.16.5-0.2.3.9-b] {re:classloading}
	at com.alaharranhonor.swem.entity.render.SWEMHorseRender.func_225623_a_(SWEMHorseRender.java:42) ~[?:1.16.5-0.2.3.9-b] {re:classloading}
	at net.minecraft.client.renderer.entity.EntityRendererManager.func_229084_a_(EntityRendererManager.java:251) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.inventory.InventoryScreen.func_241611_a_(SourceFile:149) ~[?:?] {re:classloading}
	at net.minecraft.client.gui.screen.inventory.InventoryScreen$$Lambda$8136/438452596.run(Unknown Source) ~[?:?] {}
	at com.mojang.blaze3d.systems.RenderSystem.runAsFancy(SourceFile:1439) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.client.gui.screen.inventory.InventoryScreen.func_228187_a_(SourceFile:149) ~[?:?] {re:classloading}
	at tschipp.callablehorses.client.gui.GuiStatViewer.func_230430_a_(GuiStatViewer.java:114) ~[?:1.2.1.4] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:302) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:492) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:fairylights:GameRendererTransformer,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.2.0.jar:36.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$457/464994546.call(Unknown Source) [forge-1.16.5-36.2.0.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.alaharranhonor.swem.entity.layers.HalterLayer.render(HalterLayer.java:45) ~[?:1.16.5-0.2.3.9-b] {re:classloading}
	at com.alaharranhonor.swem.entity.layers.HalterLayer.render(HalterLayer.java:32) ~[?:1.16.5-0.2.3.9-b] {re:classloading}
	at software.bernie.geckolib3.renderers.geo.GeoEntityRenderer.render(GeoEntityRenderer.java:151) ~[?:3.0.35] {re:classloading}
	at com.alaharranhonor.swem.entity.render.SWEMHorseRender.render(SWEMHorseRender.java:82) ~[?:1.16.5-0.2.3.9-b] {re:classloading}
	at com.alaharranhonor.swem.entity.render.SWEMHorseRender.func_225623_a_(SWEMHorseRender.java:42) ~[?:1.16.5-0.2.3.9-b] {re:classloading}
-- Entity being rendered --
Details:
	Entity Type: swem:swem_horse (com.alaharranhonor.swem.entities.SWEMHorseEntity)
	Entity ID: 303
	Entity Name: SWEM Horse
	Entity's Exact location: 1531.86, 64.00, 977.43
	Entity's Block location: World: (1531,64,977), Chunk: (at 11,4,1 in 95,61; contains blocks 1520,0,976 to 1535,255,991), Region: (2,1; contains chunks 64,32 to 95,63, blocks 1024,0,512 to 1535,255,1023)
	Entity's Momentum: -0.03, -0.08, -0.02
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

-- Renderer details --
Details:
	Assigned renderer: com.alaharranhonor.swem.entity.render.SWEMHorseRender@7134b9d4
	Location: 0.00,0.00,0.00 - World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Rotation: 0.0
	Delta: 1.0
Stacktrace:
	at net.minecraft.client.renderer.entity.EntityRendererManager.func_229084_a_(EntityRendererManager.java:251) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.inventory.InventoryScreen.func_241611_a_(SourceFile:149) ~[?:?] {re:classloading}
	at net.minecraft.client.gui.screen.inventory.InventoryScreen$$Lambda$8136/438452596.run(Unknown Source) ~[?:?] {}
	at com.mojang.blaze3d.systems.RenderSystem.runAsFancy(SourceFile:1439) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.client.gui.screen.inventory.InventoryScreen.func_228187_a_(SourceFile:149) ~[?:?] {re:classloading}
	at tschipp.callablehorses.client.gui.GuiStatViewer.func_230430_a_(GuiStatViewer.java:114) ~[?:1.2.1.4] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:302) ~[?:?] {re:classloading}


-- Screen render details --
Details:
	Screen name: tschipp.callablehorses.client.gui.GuiStatViewer
	Mouse location: Scaled: (267, 139). Absolute: (800.000000, 418.000000)
	Screen size: Scaled: (534, 279). Absolute: (1600, 837). Scale factor of 3.000000

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['Psychicwolf'/137, l='ClientLevel', x=1531.16, y=65.44, z=976.87]]
	Chunk stats: Client Chunk Cache: 289, 132
	Level dimension: minecraft:overworld
	Level spawn location: World: (240,69,256), Chunk: (at 0,4,0 in 15,16; contains blocks 240,0,256 to 255,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 33158 game time, 33158 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:447) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2029) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:623) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.2.0.jar:36.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$457/464994546.call(Unknown Source) [forge-1.16.5-36.2.0.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}


-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1188571912 bytes (1133 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 2
	JVM Flags: 10 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -XX:+IgnoreUnrecognizedVMOptions -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.0.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.0.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.0.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.0.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.0.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.0
	FML Language Providers: 
		javafml@36.2
		minecraft@1
	Mod List: 
		forge-1.16.5-36.2.0-client.jar                    |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
		useful_backpacks-1.16.5-1.12.1.90.jar             |Useful Backpacks              |usefulbackpacks               |1.12.1.90           |DONE      |Manifest: f4:a6:0b:ee:cb:8a:1a:ea:9f:9d:45:91:8f:8b:b3:ae:26:f3:bf:05:86:1d:90:9e:f6:32:2a:1a:ed:1d:ce:b0
		ItemBorders-1.16.5-1.1.2.jar                      |Item Borders                  |itemborders                   |1.1.2               |DONE      |Manifest: NOSIGNATURE
		InventoryHud_[1.16.2-1.16.5].forge-3.4.1.jar      |Inventory HUD+(Forge edition) |inventoryhud                  |3.4.1               |DONE      |Manifest: NOSIGNATURE
		lootbeams-1.16.5-release-nov0221.jar              |LootBeams                     |lootbeams                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
		u_team_core-1.16.5-3.2.1.196.jar                  |U Team Core                   |uteamcore                     |3.2.1.196           |DONE      |Manifest: f4:a6:0b:ee:cb:8a:1a:ea:9f:9d:45:91:8f:8b:b3:ae:26:f3:bf:05:86:1d:90:9e:f6:32:2a:1a:ed:1d:ce:b0
		Hwyla-forge-1.10.11-B78_1.16.2.jar                |Waila                         |waila                         |1.10.11-B78_1.16.2  |DONE      |Manifest: NOSIGNATURE
		fairylights-4.0.5-1.16.5.jar                      |Fairy Lights                  |fairylights                   |4.0.5               |DONE      |Manifest: NOSIGNATURE
		chat_heads_forge-0.2.0.jar                        |Chat Heads                    |chat_heads                    |0.2.0               |DONE      |Manifest: NOSIGNATURE
		callablehorses-1.16.3-1.2.1.4.jar                 |Callable Horses               |callablehorses                |1.2.1.4             |DONE      |Manifest: 8c:03:ac:7d:21:62:65:e2:83:91:f3:22:57:99:ed:75:78:1e:db:de:03:99:ef:53:3b:59:95:18:01:bc:84:a9
		forge-1.16.5-36.2.0-universal.jar                 |Forge                         |forge                         |36.2.0              |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		appleskin-forge-mc1.16.x-2.2.0.jar                |AppleSkin                     |appleskin                     |mc1.16.4-2.2.0      |DONE      |Manifest: NOSIGNATURE
		Iceberg-1.16.5-1.0.24.jar                         |Iceberg                       |iceberg                       |1.0.24              |DONE      |Manifest: NOSIGNATURE
		geckolib-forge-1.16.5-3.0.35.jar                  |GeckoLib                      |geckolib3                     |3.0.35              |DONE      |Manifest: NOSIGNATURE
		swem-1.16.5-0.2.3.9-b.jar                         |Star Worm Equestrian Mod      |swem                          |1.16.5-0.2.3.9-b    |DONE      |Manifest: NOSIGNATURE
		WailaHarvestability-mc1.16.x-forge-1.1.15.jar     |Waila Harvestability          |wailaharvestability           |1.1.15              |DONE      |Manifest: NOSIGNATURE
		EquipmentCompare-1.16.5-1.2.7.jar                 |Equipment Compare             |equipmentcompare              |1.2.7               |DONE      |Manifest: NOSIGNATURE
		StorageDrawers-1.16.3-8.3.0.jar                   |Storage Drawers               |storagedrawers                |8.3.0               |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: a728d700-ff60-4393-9248-a31e2d710710
	Launched Version: 1.16.5-forge-36.2.0
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Intel(R) HD Graphics GL version 4.0.0 - Build 10.18.10.4358, Intel
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla
	Current Language: English (US)
	CPU: 2x Intel(R) Pentium(R) CPU G2020T @ 2.50GHz
```

**Comment by MagnusHJensen** [comment]
This has been fixed with `0.2.5.3-b` and up.
