### ISSUE TITLE
[Bug]: Game Crashed

### ISSUE THREAD

**Issue by 2by2withnoah** [cavecomputing/SWEM-Beta#91]
### What happened?

My game crashed why I did F3 + T.

### What should happen?

My game should not crash.

### Mods

SWEM
GekoLib

### SWEM Version

swem-1.16.5-0.1.1.1-b.jar

### Singleplayer or Multiplayer

- [X] Singleplayer
- [ ] Multiplayer
- [ ] Other (Please add a comment to the issue where this is happening)

### OS

Windows

### Relevant log output

```shell
---- Minecraft Crash Report ----
// Don't do that.

Time: 11/5/21 5:51 PM
Description: Rendering entity in world

java.lang.NullPointerException: Rendering entity in world
	at software.bernie.shadowed.eliotlash.molang.MolangParser.getVariable(MolangParser.java:87) ~[?:3.0.35] {re:classloading}
	at software.bernie.shadowed.eliotlash.molang.MolangParser.setValue(MolangParser.java:73) ~[?:3.0.35] {re:classloading}
	at software.bernie.geckolib3.model.AnimatedGeoModel.setMolangQueries(AnimatedGeoModel.java:127) ~[?:3.0.35] {re:classloading}
	at software.bernie.geckolib3.core.processor.AnimationProcessor.preAnimationSetup(AnimationProcessor.java:296) ~[?:3.0.35] {re:classloading}
	at software.bernie.geckolib3.model.AnimatedGeoModel.setLivingAnimations(AnimatedGeoModel.java:74) ~[?:3.0.35] {re:classloading}
	at software.bernie.geckolib3.model.AnimatedGeoModel.setLivingAnimations(AnimatedGeoModel.java:32) ~[?:3.0.35] {re:classloading}
	at software.bernie.geckolib3.renderers.geo.GeoEntityRenderer.render(GeoEntityRenderer.java:136) ~[?:3.0.35] {re:classloading}
	at com.alaharranhonor.swem.entity.render.SWEMHorseRender.render(SWEMHorseRender.java:67) ~[?:1.16.5-0.1.1.0-b] {re:classloading}
	at com.alaharranhonor.swem.entity.render.SWEMHorseRender.func_225623_a_(SWEMHorseRender.java:27) ~[?:1.16.5-0.1.1.0-b] {re:classloading}
	at net.minecraft.client.renderer.entity.EntityRendererManager.func_229084_a_(EntityRendererManager.java:251) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.WorldRenderer.func_228418_a_(WorldRenderer.java:1202) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.WorldRenderer.func_228426_a_(WorldRenderer.java:1010) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:608) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:425) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.2.0.jar:36.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$441/1682619279.call(Unknown Source) [forge-1.16.5-36.2.0.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at software.bernie.shadowed.eliotlash.molang.MolangParser.getVariable(MolangParser.java:87) ~[?:3.0.35] {re:classloading}
	at software.bernie.shadowed.eliotlash.molang.MolangParser.setValue(MolangParser.java:73) ~[?:3.0.35] {re:classloading}
	at software.bernie.geckolib3.model.AnimatedGeoModel.setMolangQueries(AnimatedGeoModel.java:127) ~[?:3.0.35] {re:classloading}
	at software.bernie.geckolib3.core.processor.AnimationProcessor.preAnimationSetup(AnimationProcessor.java:296) ~[?:3.0.35] {re:classloading}
	at software.bernie.geckolib3.model.AnimatedGeoModel.setLivingAnimations(AnimatedGeoModel.java:74) ~[?:3.0.35] {re:classloading}
	at software.bernie.geckolib3.model.AnimatedGeoModel.setLivingAnimations(AnimatedGeoModel.java:32) ~[?:3.0.35] {re:classloading}
	at software.bernie.geckolib3.renderers.geo.GeoEntityRenderer.render(GeoEntityRenderer.java:136) ~[?:3.0.35] {re:classloading}
	at com.alaharranhonor.swem.entity.render.SWEMHorseRender.render(SWEMHorseRender.java:67) ~[?:1.16.5-0.1.1.0-b] {re:classloading}
	at com.alaharranhonor.swem.entity.render.SWEMHorseRender.func_225623_a_(SWEMHorseRender.java:27) ~[?:1.16.5-0.1.1.0-b] {re:classloading}
-- Entity being rendered --
Details:
	Entity Type: swem:swem_horse (com.alaharranhonor.swem.entities.SWEMHorseEntity)
	Entity ID: 30703
	Entity Name: SWEM Horse
	Entity's Exact location: 403.04, 66.00, 502.73
	Entity's Block location: World: (403,66,502), Chunk: (at 3,4,6 in 25,31; contains blocks 400,0,496 to 415,255,511), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: [ClientPlayerEntity['2by2withnoah'/21918, l='ClientLevel', x=403.13, y=67.44, z=502.77]]
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

-- Renderer details --
Details:
	Assigned renderer: com.alaharranhonor.swem.entity.render.SWEMHorseRender@17927533
	Location: -0.09,-3.06,-0.04 - World: (-1,-4,-1), Chunk: (at 15,-1,15 in -1,-1; contains blocks -16,0,-16 to -1,255,-1), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Rotation: 111.90117
	Delta: 0.94004047
Stacktrace:
	at net.minecraft.client.renderer.entity.EntityRendererManager.func_229084_a_(EntityRendererManager.java:251) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.WorldRenderer.func_228418_a_(WorldRenderer.java:1202) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.WorldRenderer.func_228426_a_(WorldRenderer.java:1010) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:608) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}


-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['2by2withnoah'/21918, l='ClientLevel', x=403.13, y=67.44, z=502.77]]
	Chunk stats: Client Chunk Cache: 729, 483
	Level dimension: minecraft:overworld
	Level spawn location: World: (240,73,-32), Chunk: (at 0,4,0 in 15,-2; contains blocks 240,0,-32 to 255,255,-17), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 113381 game time, 175869 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:447) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2029) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:623) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.2.0.jar:36.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$441/1682619279.call(Unknown Source) [forge-1.16.5-36.2.0.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}


-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 931268664 bytes (888 MB) / 3223846912 bytes (3074 MB) up to 3817865216 bytes (3641 MB)
	CPUs: 6
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m -XX:PermSize=256m
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.0.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.0.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.0.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.0.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.0.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.0
	FML Language Providers: 
		javafml@36.2
		minecraft@1
	Mod List: 
		forge-1.16.5-36.2.0-client.jar                    |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.0-universal.jar                 |Forge                         |forge                         |36.2.0              |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		geckolib-forge-1.16.5-3.0.35.jar                  |GeckoLib                      |geckolib3                     |3.0.35              |DONE      |Manifest: NOSIGNATURE
		swem-1.16.5-0.1.1.1-b.jar                         |Star Worm Equestrian Mod      |swem                          |1.16.5-0.1.1.0-b    |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 50e09c2f-7c22-44a4-9ed9-a33cdcced9bc
	Launched Version: forge-36.2.0
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce GTX 1660 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 466.77, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, mod_resources
	Current Language: English (US)
	CPU: 6x Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz
```

**Comment by MagnusHJensen** [comment]
This is unfortunately a crash within GeckoLib.

They have tried to fix it, but without any luck.
